language: java
jdk:
  - openjdk11

branches:
  only:
    - master

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_install:
  - chmod +x gradlew
# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - sskk713@ajou.ac.kr
  slack: nomadsc21:UDDaW7zIFUEeMird5gUglzXV

before_deploy:
  - zip -r nomad *
  - mkdir -p deploy
  - mv nomad.zip deploy/nomad.zip
  -
deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: leesk
    region: ap-northeast-2
    skip_cleanup: true
    acl: public_read
    local_dir: deploy
    wait-until-deployed: true
    on:
      repo: ajou-nomad/nomad-backend
      branch: master