spring:
  datasource:
    url: jdbc:mariadb://database-2.c2beaxn4glkx.ap-northeast-2.rds.amazonaws.com:3306/admin
    username: admin
    password: tkdrud11
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace