#spring:
#  datasource:
#    url: jdbc:mariadb://database-2.c2beaxn4glkx.ap-northeast-2.rds.amazonaws.com:3306/nomad_maria
#    username: admin
#    password: tkdrud11
#    driver-class-name: org.mariadb.jdbc.Driver
#
#  jpa:
#    hibernate:
#    ddl-auto: create-drop
#  properties:
#    hibernate:
#      show_sql: true
#      format_sql: true
#logging.level:
#  org.hibernate.SQL: debug
#  org.hibernate.type: trace
spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
    ddl-auto: create-drop
  properties:
    hibernate:
      show_sql: true
      format_sql: true
logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace