spring:
#  datasource:
#    url: jdbc:h2:tcp://localhost/~/test
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://database-2.c2beaxn4glkx.ap-northeast-2.rds.amazonaws.com:5432
    username: postgres
    password: tkdrud11

    hikari:
      connection-timeout: 20000
      maximum-pool-size: 10
  #JPA
  jpa:
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    show-sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual: true
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace